server:
  port: 8090
  undertow:
    accesslog:
      enabled: false

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_db?useSSL=false&nullNamePatternMatchesAll=true&maxReconnects=10&autoReconnect=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Saschko1012
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: demoCP
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 125
        prepStmtCacheSqlLimit: 1024
        useServerPrepStmts: true
      max-lifetime: 1500000
  jpa:
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

    open-in-view: false

  liquibase:
    change-log: classpath:db/db.changelog-master.xml

logging:
  config: classpath:logback-spring.xml